import os
import re
import sys
import numpy as np
import matplotlib.pyplot as plt

'''
Generated by ChatGPT.
'''

def read_pfm(file):
    """
    Read a PFM file and return image as float32 numpy array.
    """
    with open(file, 'rb') as f:
        header = f.readline().decode('utf-8').rstrip()
        if header == 'PF':
            color = True
        elif header == 'Pf':
            color = False
        else:
            raise Exception('Not a valid PFM file.')

        dims = f.readline().decode('utf-8')
        while dims.startswith('#'):
            dims = f.readline().decode('utf-8')
        width, height = map(int, dims.strip().split())

        scale = float(f.readline().decode('utf-8').strip())
        endian = '<' if scale < 0 else '>'  # little endian if negative
        scale = abs(scale)

        data = np.fromfile(f, endian + 'f')
        shape = (height, width, 3) if color else (height, width)
        data = np.reshape(data, shape)

        data = np.flipud(data)
        return data


def compute_rmse(img, ref):
    """
    Compute Root Mean Squared Error between two images.
    """
    if img.shape != ref.shape:
        raise ValueError("Image and reference must have the same shape.")
    return np.sqrt(np.mean((img - ref) ** 2))


def extract_spp(filename):
    """
    Extract spp value from filename.
    Examples supported:
        image_64spp.pfm
        render_128.pfm
    """
    match = re.search(r'(\d+)\s*(?:spp)?', filename)
    if match:
        return int(match.group(1))
    else:
        raise ValueError(f"Could not extract SPP from filename: {filename}")


def main(folder_path, reference_name="reference.pfm"):
    reference_path = os.path.join(folder_path, reference_name)

    if not os.path.exists(reference_path):
        raise FileNotFoundError(f"Reference image not found: {reference_path}")

    print("Loading reference image...")
    reference = read_pfm(reference_path)

    spp_values = []
    rmse_values = []

    for file in os.listdir(folder_path):
        if file.endswith(".pfm") and file != reference_name:
            file_path = os.path.join(folder_path, file)
            try:
                spp = extract_spp(file)
                print(f"Processing {file} (SPP={spp})")
                image = read_pfm(file_path)
                rmse = compute_rmse(image, reference)

                spp_values.append(spp)
                rmse_values.append(rmse)

            except Exception as e:
                print(f"Skipping {file}: {e}")

    if not spp_values:
        print("No valid rendered images found.")
        return

    # Sort by SPP
    spp_values = np.array(spp_values)
    rmse_values = np.array(rmse_values)
    sorted_indices = np.argsort(spp_values)

    spp_values = spp_values[sorted_indices]
    rmse_values = rmse_values[sorted_indices]

    # Plot log-log graph
    plt.figure()
    plt.loglog(spp_values, rmse_values, marker='o')
    plt.xlabel("Samples Per Pixel (SPP)")
    plt.ylabel("Root Mean Squared Error (RMSE)")
    plt.title("RMSE vs SPP (log-log scale)")
    plt.grid(True, which="both", ls="--")
    plt.savefig(folder_path + "/rmse_vs_spp.png", dpi=300, bbox_inches="tight")
    print("Plot saved as rmse_vs_spp.png")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python rmse_plot.py <folder_path> [reference_filename]")
        sys.exit(1)

    folder = sys.argv[1]
    reference_file = sys.argv[2] if len(sys.argv) > 2 else "reference.pfm"

    main(folder, reference_file)