import os
import re
import sys
import numpy as np
import matplotlib.pyplot as plt

'''
Generated by Google Gemini.
'''

def read_pfm(file):
    """
    Read a PFM file and return image as float32 numpy array.
    """
    with open(file, 'rb') as f:
        header = f.readline().decode('utf-8').rstrip()
        if header == 'PF':
            color = True
        elif header == 'Pf':
            color = False
        else:
            raise Exception('Not a valid PFM file.')

        dims = f.readline().decode('utf-8')
        while dims.startswith('#'):
            dims = f.readline().decode('utf-8')
        width, height = map(int, dims.strip().split())

        scale = float(f.readline().decode('utf-8').strip())
        endian = '<' if scale < 0 else '>'
        scale = abs(scale)

        data = np.fromfile(f, endian + 'f')
        shape = (height, width, 3) if color else (height, width)
        data = np.reshape(data, shape)

        data = np.flipud(data)
        return data

def compute_rmse(img, ref):
    """
    Compute Root Mean Squared Error between two images.
    """
    if img.shape != ref.shape:
        raise ValueError("Image and reference must have the same shape.")
    return np.sqrt(np.mean((img - ref) ** 2))

def extract_spp(filename):
    """
    Extract spp value from filename.
    Matches the pattern: render_seq[N]spp.pfm
    """
    match = re.search(r'seq_(\d+)', filename)
    if match:
        return int(match.group(1))
    else:
        raise ValueError(f"Could not extract SPP from filename: {filename}")

def main(root_path, reference_name="reference.pfm"):
    reference_path = os.path.join(root_path, reference_name)

    if not os.path.exists(reference_path):
        raise FileNotFoundError(f"Reference image not found: {reference_path}")

    print(f"Loading reference: {reference_name}")
    reference = read_pfm(reference_path)

    plt.figure(figsize=(10, 6))
    
    # Iterate through each item in the root folder
    subdirs = [d for d in os.listdir(root_path) if os.path.isdir(os.path.join(root_path, d))]
    
    if not subdirs:
        print("No sequence subdirectories found.")
        return

    for seq_name in sorted(subdirs):
        seq_path = os.path.join(root_path, seq_name)
        spp_values = []
        rmse_values = []

        print(f"Processing sequence: {seq_name}")

        for file in os.listdir(seq_path):
            if file.endswith(".pfm"):
                file_full_path = os.path.join(seq_path, file)
                try:
                    spp = extract_spp(file)
                    image = read_pfm(file_full_path)
                    rmse = compute_rmse(image, reference)

                    spp_values.append(spp)
                    rmse_values.append(rmse)
                except Exception as e:
                    print(f"  Skipping {file}: {e}")

        if spp_values:
            # Sort data points by SPP for correct line plotting
            spp_array = np.array(spp_values)
            rmse_array = np.array(rmse_values)
            sort_idx = np.argsort(spp_array)
            
            plt.loglog(spp_array[sort_idx], rmse_array[sort_idx], marker='o', label=seq_name)
        else:
            print(f"  No valid .pfm files found in {seq_name}")

    plt.xlabel("Samples Per Pixel (SPP)")
    plt.ylabel("Root Mean Squared Error (RMSE)")
    plt.title("RMSE vs SPP per Sequence (log-log scale)")
    plt.grid(True, which="both", ls="--", alpha=0.5)
    plt.legend()
    
    output_file = os.path.join(root_path, "rmse_comparison.png")
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    print(f"Comparison plot saved as {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python rmse_plot.py <folder_path> [reference_filename]")
        sys.exit(1)

    folder = sys.argv[1]
    reference_file = sys.argv[2] if len(sys.argv) > 2 else "reference.pfm"

    main(folder, reference_file)